<?php

use GlpiPlugin\Biforglpi\DashboardAccess;
use GlpiPlugin\Biforglpi\DashboardWidget;
use GlpiPlugin\Biforglpi\Navigation;
use GlpiPlugin\Biforglpi\SavedQuery;
use GlpiPlugin\Biforglpi\SqlLab;

include '../../../inc/includes.php';
$pluginUrl = Plugin::getWebDir('biforglpi');
$escapedPluginUrl = htmlspecialchars($pluginUrl, ENT_QUOTES, 'UTF-8');
$id = filter_var($_POST['id'] ?? $_GET['id'] ?? 0, FILTER_VALIDATE_INT) ?: 0;
$dashboardId = filter_var($_POST['dashboards_id'] ?? $_GET['dashboards_id'] ?? 0, FILTER_VALIDATE_INT) ?: 0;
$widget = ['id' => 0, 'savedqueries_id' => 0, 'title' => '', 'widget_type' => 'number', 'position' => 0, 'width' => 4, 'demo_data' => '', 'settings' => []];
if ($id > 0) {
    $stored = DashboardWidget::find($id);
    if ($stored === null) { http_response_code(404); exit; }
    $widget = $stored;
    $dashboardId = (int) $widget['dashboards_id'];
}
DashboardAccess::checkEdit($dashboardId);
$error = null;
$redirectUrl = null;
if (($_SERVER['REQUEST_METHOD'] ?? '') === 'POST') {
    try {
        if (isset($_POST['delete']) && $id > 0) {
            DashboardWidget::delete($id);
        } elseif (isset($_POST['save'])) {
            $id > 0 ? DashboardWidget::update($id, $_POST) : DashboardWidget::create($dashboardId, $_POST);
        }
        $redirectUrl = $pluginUrl . '/front/dashboard.form.php?id=' . $dashboardId;
    } catch (InvalidArgumentException $exception) {
        $error = $exception->getMessage();
        $widget = array_merge($widget, $_POST);
    } catch (Throwable) {
        $error = __('Não foi possível concluir a operação.', 'biforglpi');
        $widget = array_merge($widget, $_POST);
    }
    if ($redirectUrl !== null) {
        Html::redirect($redirectUrl);
    }
}
$queries = SavedQuery::all(true);
$labels = ['number' => 'Indicador numérico', 'table' => 'Tabela', 'bar' => 'Gráfico de barras', 'line' => 'Gráfico de linha', 'doughnut' => 'Gráfico de rosca', 'gauge' => 'Gauge (velocímetro)'];
$number = array_merge(DashboardWidget::defaultNumberSettings(), $widget['widget_type'] === 'number' && is_array($widget['settings'] ?? null) ? $widget['settings'] : []);
foreach (array_keys($number) as $setting) {
    if (array_key_exists('number_' . $setting, $widget)) {
        $number[$setting] = $widget['number_' . $setting];
    }
}
$bar = array_merge(DashboardWidget::defaultBarSettings(), $widget['widget_type'] === 'bar' && is_array($widget['settings'] ?? null) ? $widget['settings'] : []);
foreach (array_keys($bar) as $setting) {
    if (array_key_exists('bar_' . $setting, $widget)) {
        $bar[$setting] = $widget['bar_' . $setting];
    }
}
$line = array_merge(DashboardWidget::defaultLineSettings(), $widget['widget_type'] === 'line' && is_array($widget['settings'] ?? null) ? $widget['settings'] : []);
foreach (array_keys($line) as $setting) {
    if (array_key_exists('line_' . $setting, $widget)) {
        $line[$setting] = $widget['line_' . $setting];
    }
}
$doughnut = array_merge(DashboardWidget::defaultDoughnutSettings(), $widget['widget_type'] === 'doughnut' && is_array($widget['settings'] ?? null) ? $widget['settings'] : []);
foreach (array_keys($doughnut) as $setting) {
    if (array_key_exists('doughnut_' . $setting, $widget)) {
        $doughnut[$setting] = $widget['doughnut_' . $setting];
    }
}
$gauge = array_merge(DashboardWidget::defaultGaugeSettings(), is_array($widget['settings'] ?? null) ? $widget['settings'] : []);
foreach (array_keys($gauge) as $setting) {
    if (array_key_exists('gauge_' . $setting, $widget)) {
        $gauge[$setting] = $widget['gauge_' . $setting];
    }
}
Html::header(__('BI for GLPI', 'biforglpi'), $_SERVER['PHP_SELF'], 'tools', SqlLab::class);
?>
<main class="biforglpi-lab container-xl"><?php Navigation::render('dashboards'); ?><div class="biforglpi-page-heading"><div><h1><?= $id ? __('Editar componente', 'biforglpi') : __('Novo componente', 'biforglpi') ?></h1><p class="text-secondary mb-0"><?= __('Associe uma consulta a uma visualização do dashboard.', 'biforglpi') ?></p></div></div>
<?php if ($error): ?><div class="alert alert-danger"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
<section class="card biforglpi-card"><div class="card-body"><form method="post" action="<?= $escapedPluginUrl ?>/front/widget.form.php"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="dashboards_id" value="<?= $dashboardId ?>">
<div class="mb-3"><label class="form-label" for="widget-query"><?= __('Consulta salva', 'biforglpi') ?></label><select class="form-select" id="widget-query" name="savedqueries_id" required><option value=""><?= __('Selecione', 'biforglpi') ?></option><?php foreach ($queries as $query): ?><option value="<?= $query['id'] ?>" <?= (int) $widget['savedqueries_id'] === (int) $query['id'] ? 'selected' : '' ?>><?= htmlspecialchars((string) $query['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
<div class="mb-3"><label class="form-label" for="widget-title"><?= __('Título opcional', 'biforglpi') ?></label><input class="form-control" id="widget-title" name="title" maxlength="255" value="<?= htmlspecialchars((string) ($widget['title'] ?? ''), ENT_QUOTES, 'UTF-8') ?>"></div>
<div class="row g-3"><div class="col-md-4"><label class="form-label" for="widget-type"><?= __('Visualização', 'biforglpi') ?></label><select class="form-select" id="widget-type" name="widget_type"><?php foreach ($labels as $type => $label): ?><option value="<?= $type ?>" <?= $widget['widget_type'] === $type ? 'selected' : '' ?>><?= __($label, 'biforglpi') ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label" for="widget-width"><?= __('Largura', 'biforglpi') ?></label><select class="form-select" id="widget-width" name="width"><?php foreach ([3,4,6,8,12] as $width): ?><option value="<?= $width ?>" <?= (int) $widget['width'] === $width ? 'selected' : '' ?>><?= $width ?>/12</option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label" for="widget-position"><?= __('Posição', 'biforglpi') ?></label><input class="form-control" id="widget-position" name="position" type="number" min="0" max="999" value="<?= (int) $widget['position'] ?>"></div></div>
<fieldset class="card mt-3 <?= $widget['widget_type'] === 'number' ? '' : 'd-none' ?>" id="biforglpi-number-settings" <?= $widget['widget_type'] === 'number' ? '' : 'hidden' ?>><div class="card-body"><legend class="h3 mb-3"><?= __('Formatação do indicador numérico', 'biforglpi') ?></legend>
<div class="row g-3"><div class="col-md-3"><label class="form-label" for="number-decimals"><?= __('Casas decimais', 'biforglpi') ?></label><select class="form-select" id="number-decimals" name="number_decimals"><option value="-1" <?= (int) $number['decimals'] === -1 ? 'selected' : '' ?>><?= __('Automático', 'biforglpi') ?></option><?php for ($decimals = 0; $decimals <= 6; $decimals++): ?><option value="<?= $decimals ?>" <?= (int) $number['decimals'] === $decimals ? 'selected' : '' ?>><?= $decimals ?></option><?php endfor; ?></select></div><div class="col-md-3"><label class="form-label" for="number-prefix"><?= __('Prefixo', 'biforglpi') ?></label><input class="form-control" id="number-prefix" name="number_prefix" maxlength="20" value="<?= htmlspecialchars((string) $number['prefix'], ENT_QUOTES, 'UTF-8') ?>" placeholder="R$ "></div><div class="col-md-3"><label class="form-label" for="number-suffix"><?= __('Sufixo', 'biforglpi') ?></label><input class="form-control" id="number-suffix" name="number_suffix" maxlength="20" value="<?= htmlspecialchars((string) $number['suffix'], ENT_QUOTES, 'UTF-8') ?>" placeholder="%"></div><div class="col-md-3"><label class="form-label" for="number-target"><?= __('Meta opcional', 'biforglpi') ?></label><input class="form-control" id="number-target" name="number_target" type="number" step="any" value="<?= htmlspecialchars((string) ($number['target'] ?? ''), ENT_QUOTES, 'UTF-8') ?>"></div></div>
<div class="mt-3"><label class="form-check"><input type="hidden" name="number_use_colors" value="0"><input class="form-check-input" type="checkbox" name="number_use_colors" value="1" <?= !empty($number['use_colors']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Aplicar cores conforme o valor', 'biforglpi') ?></span></label></div>
<div class="row g-3 mt-1"><div class="col-md-3"><label class="form-label" for="number-warning"><?= __('Início da faixa de atenção', 'biforglpi') ?></label><input class="form-control" id="number-warning" name="number_warning" type="number" step="any" value="<?= htmlspecialchars((string) $number['warning'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label class="form-label" for="number-success"><?= __('Início da faixa de sucesso', 'biforglpi') ?></label><input class="form-control" id="number-success" name="number_success" type="number" step="any" value="<?= htmlspecialchars((string) $number['success'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-2"><label class="form-label" for="number-color-low"><?= __('Cor crítica', 'biforglpi') ?></label><input class="form-control form-control-color" id="number-color-low" name="number_color_low" type="color" value="<?= htmlspecialchars((string) $number['color_low'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-2"><label class="form-label" for="number-color-mid"><?= __('Cor de atenção', 'biforglpi') ?></label><input class="form-control form-control-color" id="number-color-mid" name="number_color_mid" type="color" value="<?= htmlspecialchars((string) $number['color_mid'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-2"><label class="form-label" for="number-color-high"><?= __('Cor de sucesso', 'biforglpi') ?></label><input class="form-control form-control-color" id="number-color-high" name="number_color_high" type="color" value="<?= htmlspecialchars((string) $number['color_high'], ENT_QUOTES, 'UTF-8') ?>"></div></div>
<div class="form-hint mt-3"><?= __('Prefixo e sufixo são exibidos exatamente como informados. As cores consideram que valores maiores são melhores.', 'biforglpi') ?></div></div></fieldset>
<fieldset class="card mt-3 <?= $widget['widget_type'] === 'bar' ? '' : 'd-none' ?>" id="biforglpi-bar-settings" <?= $widget['widget_type'] === 'bar' ? '' : 'hidden' ?>><div class="card-body"><legend class="h3 mb-3"><?= __('Configuração do gráfico de barras', 'biforglpi') ?></legend>
<div class="row g-3"><div class="col-md-3"><label class="form-label" for="bar-orientation"><?= __('Orientação', 'biforglpi') ?></label><select class="form-select" id="bar-orientation" name="bar_orientation"><option value="vertical" <?= $bar['orientation'] === 'vertical' ? 'selected' : '' ?>><?= __('Vertical', 'biforglpi') ?></option><option value="horizontal" <?= $bar['orientation'] === 'horizontal' ? 'selected' : '' ?>><?= __('Horizontal', 'biforglpi') ?></option></select></div><div class="col-md-3"><label class="form-label" for="bar-color"><?= __('Cor principal', 'biforglpi') ?></label><input class="form-control form-control-color" id="bar-color" name="bar_color" type="color" value="<?= htmlspecialchars((string) $bar['color'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label class="form-label" for="bar-decimals"><?= __('Casas decimais', 'biforglpi') ?></label><select class="form-select" id="bar-decimals" name="bar_decimals"><option value="-1" <?= (int) $bar['decimals'] === -1 ? 'selected' : '' ?>><?= __('Automático', 'biforglpi') ?></option><?php for ($decimals = 0; $decimals <= 6; $decimals++): ?><option value="<?= $decimals ?>" <?= (int) $bar['decimals'] === $decimals ? 'selected' : '' ?>><?= $decimals ?></option><?php endfor; ?></select></div><div class="col-md-3"><label class="form-label" for="bar-unit"><?= __('Unidade ou sufixo', 'biforglpi') ?></label><input class="form-control" id="bar-unit" name="bar_unit" maxlength="20" value="<?= htmlspecialchars((string) $bar['unit'], ENT_QUOTES, 'UTF-8') ?>" placeholder="%"></div></div>
<div class="d-flex flex-wrap gap-4 mt-3"><label class="form-check"><input type="hidden" name="bar_show_values" value="0"><input class="form-check-input" type="checkbox" name="bar_show_values" value="1" <?= !empty($bar['show_values']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir valores', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="bar_show_grid" value="0"><input class="form-check-input" type="checkbox" name="bar_show_grid" value="1" <?= !empty($bar['show_grid']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir grade e escala', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="bar_use_palette" value="0"><input class="form-check-input" type="checkbox" name="bar_use_palette" value="1" <?= !empty($bar['use_palette']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Usar uma cor por barra', 'biforglpi') ?></span></label></div>
<div class="form-hint mt-3"><?= __('A orientação horizontal é recomendada quando os rótulos são longos, como nomes de grupos.', 'biforglpi') ?></div></div></fieldset>
<fieldset class="card mt-3 <?= $widget['widget_type'] === 'line' ? '' : 'd-none' ?>" id="biforglpi-line-settings" <?= $widget['widget_type'] === 'line' ? '' : 'hidden' ?>><div class="card-body"><legend class="h3 mb-3"><?= __('Configuração do gráfico de linha', 'biforglpi') ?></legend>
<div class="row g-3"><div class="col-md-4"><label class="form-label" for="line-color"><?= __('Cor da linha', 'biforglpi') ?></label><input class="form-control form-control-color" id="line-color" name="line_color" type="color" value="<?= htmlspecialchars((string) $line['color'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-4"><label class="form-label" for="line-decimals"><?= __('Casas decimais', 'biforglpi') ?></label><select class="form-select" id="line-decimals" name="line_decimals"><option value="-1" <?= (int) $line['decimals'] === -1 ? 'selected' : '' ?>><?= __('Automático', 'biforglpi') ?></option><?php for ($decimals = 0; $decimals <= 6; $decimals++): ?><option value="<?= $decimals ?>" <?= (int) $line['decimals'] === $decimals ? 'selected' : '' ?>><?= $decimals ?></option><?php endfor; ?></select></div><div class="col-md-4"><label class="form-label" for="line-unit"><?= __('Unidade ou sufixo', 'biforglpi') ?></label><input class="form-control" id="line-unit" name="line_unit" maxlength="20" value="<?= htmlspecialchars((string) $line['unit'], ENT_QUOTES, 'UTF-8') ?>" placeholder="%"></div></div>
<div class="d-flex flex-wrap gap-4 mt-3"><label class="form-check"><input type="hidden" name="line_show_grid" value="0"><input class="form-check-input" type="checkbox" name="line_show_grid" value="1" <?= !empty($line['show_grid']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir grade e escala', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="line_show_values" value="0"><input class="form-check-input" type="checkbox" name="line_show_values" value="1" <?= !empty($line['show_values']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir valores', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="line_show_points" value="0"><input class="form-check-input" type="checkbox" name="line_show_points" value="1" <?= !empty($line['show_points']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir pontos', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="line_fill_area" value="0"><input class="form-check-input" type="checkbox" name="line_fill_area" value="1" <?= !empty($line['fill_area']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Preencher área', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="line_smooth" value="0"><input class="form-check-input" type="checkbox" name="line_smooth" value="1" <?= !empty($line['smooth']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Suavizar linha', 'biforglpi') ?></span></label></div>
<div class="form-hint mt-3"><?= __('Use linhas para evolução temporal. A consulta deve ordenar corretamente os períodos.', 'biforglpi') ?></div></div></fieldset>
<fieldset class="card mt-3 <?= $widget['widget_type'] === 'doughnut' ? '' : 'd-none' ?>" id="biforglpi-doughnut-settings" <?= $widget['widget_type'] === 'doughnut' ? '' : 'hidden' ?>><div class="card-body"><legend class="h3 mb-3"><?= __('Configuração do gráfico de rosca', 'biforglpi') ?></legend>
<div class="row g-3"><div class="col-md-3"><label class="form-label" for="doughnut-legend-position"><?= __('Posição da legenda', 'biforglpi') ?></label><select class="form-select" id="doughnut-legend-position" name="doughnut_legend_position"><option value="right" <?= $doughnut['legend_position'] === 'right' ? 'selected' : '' ?>><?= __('À direita', 'biforglpi') ?></option><option value="bottom" <?= $doughnut['legend_position'] === 'bottom' ? 'selected' : '' ?>><?= __('Abaixo', 'biforglpi') ?></option><option value="hidden" <?= $doughnut['legend_position'] === 'hidden' ? 'selected' : '' ?>><?= __('Oculta', 'biforglpi') ?></option></select></div><div class="col-md-3"><label class="form-label" for="doughnut-hole-size"><?= __('Tamanho do centro (%)', 'biforglpi') ?></label><input class="form-control" id="doughnut-hole-size" name="doughnut_hole_size" type="number" min="20" max="70" value="<?= (int) $doughnut['hole_size'] ?>"></div><div class="col-md-3"><label class="form-label" for="doughnut-decimals"><?= __('Casas decimais', 'biforglpi') ?></label><select class="form-select" id="doughnut-decimals" name="doughnut_decimals"><option value="-1" <?= (int) $doughnut['decimals'] === -1 ? 'selected' : '' ?>><?= __('Automático', 'biforglpi') ?></option><?php for ($decimals = 0; $decimals <= 6; $decimals++): ?><option value="<?= $decimals ?>" <?= (int) $doughnut['decimals'] === $decimals ? 'selected' : '' ?>><?= $decimals ?></option><?php endfor; ?></select></div><div class="col-md-3"><label class="form-label" for="doughnut-unit"><?= __('Unidade ou sufixo', 'biforglpi') ?></label><input class="form-control" id="doughnut-unit" name="doughnut_unit" maxlength="20" value="<?= htmlspecialchars((string) $doughnut['unit'], ENT_QUOTES, 'UTF-8') ?>" placeholder="%"></div></div>
<div class="d-flex flex-wrap gap-4 mt-3"><label class="form-check"><input type="hidden" name="doughnut_show_labels" value="0"><input class="form-check-input" type="checkbox" name="doughnut_show_labels" value="1" <?= !empty($doughnut['show_labels']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir rótulos', 'biforglpi') ?></span></label><label class="form-check"><input type="hidden" name="doughnut_show_percentages" value="0"><input class="form-check-input" type="checkbox" name="doughnut_show_percentages" value="1" <?= !empty($doughnut['show_percentages']) ? 'checked' : '' ?>><span class="form-check-label"><?= __('Exibir percentuais nos rótulos', 'biforglpi') ?></span></label></div>
<div class="form-hint mt-3"><?= __('A primeira coluna da consulta identifica as categorias e a segunda fornece os valores da rosca.', 'biforglpi') ?></div></div></fieldset>
<fieldset class="card mt-3 <?= $widget['widget_type'] === 'gauge' ? '' : 'd-none' ?>" id="biforglpi-gauge-settings" <?= $widget['widget_type'] === 'gauge' ? '' : 'hidden' ?>><div class="card-body"><legend class="h3 mb-3"><?= __('Configuração do Gauge', 'biforglpi') ?></legend>
<div class="row g-3"><div class="col-md-3"><label class="form-label" for="gauge-min"><?= __('Mínimo', 'biforglpi') ?></label><input class="form-control" id="gauge-min" name="gauge_min" type="number" step="any" value="<?= htmlspecialchars((string) $gauge['min'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label class="form-label" for="gauge-max"><?= __('Máximo', 'biforglpi') ?></label><input class="form-control" id="gauge-max" name="gauge_max" type="number" step="any" value="<?= htmlspecialchars((string) $gauge['max'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label class="form-label" for="gauge-target"><?= __('Meta', 'biforglpi') ?></label><input class="form-control" id="gauge-target" name="gauge_target" type="number" step="any" value="<?= htmlspecialchars((string) ($gauge['target'] ?? ''), ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label class="form-label" for="gauge-unit"><?= __('Unidade', 'biforglpi') ?></label><input class="form-control" id="gauge-unit" name="gauge_unit" maxlength="20" value="<?= htmlspecialchars((string) $gauge['unit'], ENT_QUOTES, 'UTF-8') ?>" placeholder="%"></div></div>
<div class="row g-3 mt-1"><div class="col-md-3"><label class="form-label" for="gauge-warning"><?= __('Início da faixa de atenção', 'biforglpi') ?></label><input class="form-control" id="gauge-warning" name="gauge_warning" type="number" step="any" value="<?= htmlspecialchars((string) $gauge['warning'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-3"><label class="form-label" for="gauge-success"><?= __('Início da faixa de sucesso', 'biforglpi') ?></label><input class="form-control" id="gauge-success" name="gauge_success" type="number" step="any" value="<?= htmlspecialchars((string) $gauge['success'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-2"><label class="form-label" for="gauge-color-low"><?= __('Cor crítica', 'biforglpi') ?></label><input class="form-control form-control-color" id="gauge-color-low" name="gauge_color_low" type="color" value="<?= htmlspecialchars((string) $gauge['color_low'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-2"><label class="form-label" for="gauge-color-mid"><?= __('Cor de atenção', 'biforglpi') ?></label><input class="form-control form-control-color" id="gauge-color-mid" name="gauge_color_mid" type="color" value="<?= htmlspecialchars((string) $gauge['color_mid'], ENT_QUOTES, 'UTF-8') ?>"></div><div class="col-md-2"><label class="form-label" for="gauge-color-high"><?= __('Cor de sucesso', 'biforglpi') ?></label><input class="form-control form-control-color" id="gauge-color-high" name="gauge_color_high" type="color" value="<?= htmlspecialchars((string) $gauge['color_high'], ENT_QUOTES, 'UTF-8') ?>"></div></div>
<div class="form-hint mt-3"><?= __('A consulta deve retornar um único valor numérico. As faixas seguem a ordem: crítica, atenção e sucesso.', 'biforglpi') ?></div></div></fieldset>
<div class="mt-3"><label class="form-label" for="widget-demo"><?= __('Dados de demonstração (JSON)', 'biforglpi') ?></label><textarea class="form-control font-monospace" id="widget-demo" name="demo_data" rows="7" placeholder='[{"mes":"Jan","valor":18}]'><?= htmlspecialchars((string) ($widget['demo_data'] ?? ''), ENT_QUOTES, 'UTF-8') ?></textarea><div class="form-hint"><?= __('Use uma lista de objetos. Para gráficos, a primeira coluna será o rótulo e a segunda o valor.', 'biforglpi') ?></div></div>
<div class="mt-4 d-flex gap-2"><button class="btn btn-primary" name="save" value="1"><?= __('Salvar componente', 'biforglpi') ?></button><a class="btn btn-outline-secondary" href="<?= $escapedPluginUrl ?>/front/dashboard.form.php?id=<?= $dashboardId ?>"><?= __('Cancelar', 'biforglpi') ?></a><?php if ($id): ?><button class="btn btn-outline-danger ms-auto" name="delete" value="1"><?= __('Excluir', 'biforglpi') ?></button><?php endif; ?></div><?php Html::closeForm(); ?></div></section></main>
<?php Html::footer(); ?>
